# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker-compose configuration file
version: "3.2"

services:
  jupyterhub:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: walki12/jupyterhub:latest
    container_name: jupyterhub
    volumes:
      - type: bind
        source: ./jupyterhub_config.py
        target: /srv/jupyterhub/jupyterhub_config.py
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      # - type: volume
      #   source: jupyteruser
      #   target: /jupyterUsers
      #   volume:
      #     nocopy: true
      # - type: volume
      #   source: jupyterhub
      #   target: /data
      #   volume:
      #     nocopy: true
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      placement:
        constraints:
          - node.hostname == jupyterhub-main
    command: >
      start.sh

# volumes:
#   jupyterhub:
#     external:
#       name: jupyterhub-data
#   jupyteruser:
#     external:
#       name: jupyterhub-userdata
# networks:
#   default:
#     external:
#       name: jupyterhub-network
