# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker-compose configuration file
version: "3.2"

services:
  jupyterhub:
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
    image: walki12/jupyterhub
    container_name: jupyterhub
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: nfs-user
        target: /exports/jupyter
        volume: 
          nocopy: true
      - type: volume
        source: nfs
        target: /data
        volume: 
          nocopy: true
    ports:
      - "443:443"
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      placement:
        constraints:
          - node.role == manager
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py

volumes:
  nfs:
    driver: local
    driver_opts: 
      type: nfs
      o: addr=10.15.202.10,rw
      device: ":/exports/jupyterhub"
  nfs-user:
    driver: local
    driver_opts: 
      type: nfs
      o: addr=10.15.202.10,rw
      device: ":/exports/jupyter"
networks:
  default:
    external: 
      name: jupyterhub-network
